# Generated by Django 5.1.5 on 2025-01-27 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contacts_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
