# Generated by Django 5.1.5 on 2025-01-28 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
